<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Platforms>x64</Platforms>
    <LangVersion>9.0</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>DynamicCombat</AssemblyName>
    <RootNamespace>DynamicCombat</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildProjectName)\bin\Win64_Shipping_Client\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>DummyDependencies\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>DummyDependencies\TaleWorlds.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>DummyDependencies\TaleWorlds.Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>DummyDependencies\TaleWorlds.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>DummyDependencies\TaleWorlds.Library.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>DummyDependencies\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>DummyDependencies\TaleWorlds.DotNet.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>DummyDependencies\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Audio">
      <HintPath>DummyDependencies\TaleWorlds.Audio.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <PackageReference Include="Lib.Harmony" Version="2.2.2" IncludeAssets="compile" />
    <Reference Include="MCMv5">
      <HintPath>DummyDependencies\MCMv5.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MCMv5.UI">
      <HintPath>DummyDependencies\MCMv5.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
